export const data=[
    {
      "Message": "Number of pincode(s) found:26",
      "Status": "Success",
      "PostOffice": [
        {
          "Name": "Araghar",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "BranchType": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Arahat Bazar",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Balawala",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehardun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Ballupur",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Bhaniawala",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Rishieksh",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Cannaught Place",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "CDA(A.F)",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Dalanwala",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Dehradun ",
          "Description": null,
          "BranchType": "Head Post Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Dehradun City",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Dehradun Kty",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Dilaram Bazar",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Govindgarh (Dehradun)",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Harrawala",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Hathi Barkala",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "K.P.Kshetra",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Rishikesh",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Kanwali",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Kanwali Road",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Karanpur",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Mothrowala",
          "Description": null,
          "BranchType": "Branch Office directly a/w Head Office",
          "DeliveryStatus": "Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Neshvilla Road",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Nivh",
          "Description": null,
          "BranchType": "Branch Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Patel Nagar (Dehradun)",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Rispana",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Sachivalaya Parisar",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        },
        {
          "Name": "Sayedwala",
          "Description": null,
          "BranchType": "Sub Post Office",
          "DeliveryStatus": "Non-Delivery",
          "Circle": "Uttarakhand",
          "District": "Dehradun",
          "Division": "Dehradun",
          "Region": "Dehradun",
          "Block": "Dehradun",
          "State": "Uttarakhand",
          "Country": "India",
          "Pincode": "248001"
        }
      ]
    }
  ]